### ISSUE TITLE
Couldn’t connect to rutorrent

### ISSUE THREAD

**Issue by MathieuGery** [gutenye/dockerfiles#1]
In the docker compose Port 50000 is expose instead of 5000 is it normal ?
Thanks for arm compatibility it helps me a lot <3

**Comment by gutenye** [comment]
The port number depends on your [rtorrent settings](https://wiki.archlinux.org/index.php/RTorrent#Port_configuration), there is no fixed number, please adjust by your own needs.

**Comment by MathieuGery** [comment]
I'm talking about the port for webui

**Comment by gutenye** [comment]
@MathieuGery Can you send a pull request?

**Comment by MathieuGery** [comment]
yes nopb i will work on that
